fix: webhook integration test failing with appsflyer error (#6678)
🔒 Scanned for secrets using gitleaks 8.30.0

# Description

getting the latest rudder-transformer/go version for [fixing
typo](https://github.com/rudderlabs/rudder-transformer/pull/4948)

```
=== FAIL: gateway/webhook TestIntegrationWebhook/appsflyer/test-2 (0.01s)
    integration_test.go:199: writeKey: BJeFBuqaSh
    integration_test.go:200: sourceID: DzCpwoncBx
    integration_test.go:201: workspaceID: zSUsjECYQv
    integration_test.go:212: Request URL: http://localhost:37633/v1/webhook?writeKey=BJeFBuqaSh
2026-02-12T06:09:18.261Z	ERROR	gateway.webhook	webhook/webhook.go:485	webhook source transformation failed	{"sourceType": "APPSFLYER", "errorMsg": "Unknown event type from Appsflyer", "statusCode": 400}
2026-02-12T06:09:18.261Z	INFO	gateway.webhook	webhook/webhook.go:244	IP -- Response	{"ip": "192.0.2.30", "path": "/v1/webhook", "code": 400, "error": "Unknown event type from Appsflyer"}
    integration_test.go:236: 
        	Error Trace:	/home/runner/work/rudder-server/rudder-server/gateway/webhook/integration_test.go:236
        	Error:      	Not equal: 
        	            	expected: "\"unknwon event type from appsflyer\\n\""
        	            	actual  : "\"unknown event type from appsflyer\\n\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-"unknwon event type from appsflyer\n"
        	            	+"unknown event type from appsflyer\n"
        	Test:       	TestIntegrationWebhook/appsflyer/test-2
    --- FAIL: TestIntegrationWebhook/appsflyer/test-2 (0.01s)
```

## Security

- [x] The code changed/added as part of this pull request won't create
any security issues with how the software is being used.